    	</div>
    	<!--  content end -->

    	<!-- footer begin -->
    	<div id="footer">
        	<ul>
            	<li class="first"><a href="/about/">About</a></li>
            	<li><a href="/contact/">Contact</a></li>
            	<li><a href="/terms/">Terms of Use</a></li>
       		</ul>
    	</div>
    	<!-- footer end -->

    </div>
    <!-- container end -->
    
    <div id="shadow"></div>
</body>

<!-- google analytics -->
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script>
<script type="text/javascript">
_uacct = "UA-899572-1";
urchinTracker();
</script>

<!-- TODO: only include if article? -->
<!-- syntax highlighter -->
<link type="text/css" rel="stylesheet" href="/stylesheets/SyntaxHighlighter.css"></link>
<script language="javascript" src="/javascript/shCore.js"></script>
<script language="javascript" src="/javascript/shBrushXml.js"></script>
<script language="javascript" src="/javascript/shBrushJava.js"></script>
<script language="javascript" src="/javascript/shBrushPhp.js"></script>
<script language="javascript" src="/javascript/shBrushPython.js"></script>
<script language="javascript">
dp.SyntaxHighlighter.ClipboardSwf = '/javascript/clipboard.swf';
dp.SyntaxHighlighter.HighlightAll('code');
</script>

</html>
